#!/bin/sh /etc/rc.common
# cfengine
 
START=90
STOP=10
 
start() {
    echo start
    mkdir -p /var/cfengine/bin
    cp /opt/cfengine/bin/cf-promises /var/cfengine/bin/cf-promises
    cp -r /opt/cfengine/ppkeys /var/cfengine/
    chmod 700 /var/cfengine/ppkeys
    /opt/cfengine/bootstrap.cf
    echo started.

    # fuckin ethernets on apu board hang - bootstrap again
    #sleep 120
    #/opt/cfengine/bootstrap.cf
}
 
