#!/bin/ash

task=$1

if [[ $task == 'sslcerts' ]]; then

    hostid=$(find /box/ssl -name '*-private_key.pem' | sed -n 's#/box/ssl/\(.*\)\-private_key\.pem#\1#p')

    cp "/box/ssl/ca.pem" /tmp/
    cp "/box/ssl/$hostid-*.pem" /tmp/

    cd /tmp
    zip "sslcerts-$hostid.zip" *.pem

    rm /tmp/*.pem

fi



if [[ $task == 'emails' ]]; then

    cd /box/vmail/
    tar czvf /tmp/emails.tar.gz mail/

fi

