#!/bin/ash

find_usb() {
    [[ $(cat /etc/enigmabox/network-profile) == 'raspi' ]] && start_part=a || start_part=b
    [[ $(find /dev/sd[$start_part-z] 2> /dev/null | tail -n 1 | wc -l) -gt 0 ]] || exit
    find /dev/sd[$start_part-z] | tail -n 1 | xargs fdisk -l 2> /dev/null | grep 'Disk /dev' | cut -d' ' -f2 | cut -d: -f1
}

task=$1

if [[ $task == 'sslcerts' ]]; then

    hostid=$(unzip -l /tmp/sslcerts-*.zip | grep cert.pem | awk '{ print $4 }' | cut -d- -f1)
    [[ -z $hostid ]] && exit 1

    cd /tmp
    unzip "sslcerts-$hostid.zip"

    # delete old certs
    rm "/box/ssl/ca.pem"
    rm "/box/ssl/*-cert.pem"
    rm "/box/ssl/*-public_key.pem"
    rm "/box/ssl/*-private_key.pem"

    # mkdir
    mkdir -p /box/ssl

    # copy certs
    mv "/tmp/ca.pem" "/box/ssl/"
    mv "/tmp/$hostid-cert.pem" "/box/ssl/"
    mv "/tmp/$hostid-public_key.pem" "/box/ssl/"
    mv "/tmp/$hostid-private_key.pem" "/box/ssl/"

    # inform webinterface
    curl --data "key=hostid&value=$hostid" -X POST http://127.0.0.1:8000/api/v1/set_option &> /dev/null

    # refresh server.json
    /usr/sbin/request-serverjson.py
    /usr/sbin/cfengine-apply
    /usr/sbin/request-internet.py &

    rm "/tmp/sslcerts-$hostid.zip"

fi



if [[ $task == 'emails' ]]; then

    rm -rf /box/vmail/mail
    tar xzf /tmp/emails.tar.gz -C /box/vmail
    chown -R exim:exim /box/vmail

fi



if [[ $task == 'check_usb' ]]; then

    if [[ $(find_usb | wc -l) -gt 0 ]]; then
        echo yes
    else
        echo nodrive
    fi

fi

restore_start() {
    touch /tmp/restore-in-progress
}

restore_end() {
    umount /mnt || umount -l /mnt
    rm /tmp/restore-in-progress
}

if [[ $task == 'usbstick' ]]; then

    [[ $(find_usb | wc -l) -gt 0 ]] || exit 1

    restore_start

    mount -o ro $(find_usb)1 /mnt || (restore_end ; exit 1)
    rsync -Pah /mnt/etc/enigmabox/addressbook.db /etc/enigmabox/
    rsync -Pah /mnt/box/teletext.db /box/
    rsync -Pah /mnt/box/ssl/ /box/ssl/
    rsync -Pah /mnt/box/vmail/mail/ /box/vmail/mail/
    rsync -Pah /mnt/box/roundcube.sqlite /box/
    rsync -Pah /mnt/box/settings.sqlite /box/
    rsync -Pah /mnt/teletext-avatars/ /opt/enigmabox/teletext/public/img/profile/

    chown -R root:www-data /etc/enigmabox/addressbook.db
    chown -R root:www-data /box/teletext.db
    chown -R exim:exim /box/vmail
    chown -R root:www-data /box/roundcube.sqlite
    chown -R root:www-data /box/settings.sqlite
    chown -R root:www-data /opt/enigmabox/teletext/public/img/profile/

    sync
    umount /mnt || umount -l /mnt

    /etc/init.d/lighttpd stop

    /etc/init.d/webinterface restart
    /etc/init.d/teletext restart

    usermod -p $(curl http://127.0.0.1:8000/api/v1/get_hashed_rootpw) root

    /usr/sbin/request-serverjson.py
    /usr/sbin/cfengine-apply
    /usr/sbin/request-internet.py &

    /etc/init.d/lighttpd start

    restore_end

fi

