#!/bin/ash

task=$1

if [[ $task == 'sslcerts' ]]; then

    hostid=$(unzip -l /tmp/sslcerts-*.zip | grep cert.pem | awk '{ print $4 }' | cut -d- -f1)
    [[ -z $hostid ]] && exit 1

    cd /tmp
    unzip "sslcerts-$hostid.zip"

    # delete old certs
    rm "/box/ssl/ca.pem"
    rm "/box/ssl/*-cert.pem"
    rm "/box/ssl/*-public_key.pem"
    rm "/box/ssl/*-private_key.pem"

    # mkdir
    mkdir -p /box/ssl

    # copy certs
    mv "/tmp/ca.pem" "/box/ssl/"
    mv "/tmp/$hostid-cert.pem" "/box/ssl/"
    mv "/tmp/$hostid-public_key.pem" "/box/ssl/"
    mv "/tmp/$hostid-private_key.pem" "/box/ssl/"

    # inform webinterface
    curl --data "key=hostid&value=$hostid" -X POST http://127.0.0.1:8000/api/v1/set_option &> /dev/null

    # refresh server.json
    /usr/sbin/request-serverjson.py
    /usr/sbin/cfengine-apply
    /usr/sbin/request-internet.py &

    rm "/tmp/sslcerts-$hostid.zip"

fi



if [[ $task == 'emails' ]]; then

    rm -rf /box/vmail/mail
    tar xzf /tmp/emails.tar.gz -C /box/vmail
    chown -R vmail:vmail /box/vmail

fi

