#!/bin/ash

#set -xv

# variables
opkg="/bin/opkg -f /etc/opkg-enigmabox.conf"
webinterface="http://127.0.0.1:8000"
pidfile="/var/run/updater.pid"
dynamic_output="/tmp/dynamic_output"
updates_output="/tmp/updates_output"



run() {
    background=""

    if [[ "$2" == "bg" ]]; then
        > "$dynamic_output"
        background=1
    fi

    if [[ "$1" == "check" ]]; then
        $opkg update
        $opkg list-upgradable | tee "$updates_output"

    elif [[ "$1" == "apply" ]]; then
        if [[ "$background" == 1 ]]; then
            (updater_apply > "$dynamic_output") &
        else
            updater_apply
        fi

    fi

}

inform_webinterface() {
    curl --data "key=updater_running&value=False" -X POST "$webinterface/api/v1/set_option" &> /dev/null
}



updater_apply() {
    IFS="
    "

    # upgrade every upgradable package
    for package in $(cat "$updates_output"); do
        pkg=$(echo "$package" | cut -d' ' -f1)
        $opkg upgrade "$pkg"
    done

    # remove and reinstall webinterface
    rm -rf /opt/enigmabox/webinterface
    $opkg install webinterface --force-reinstall

    # reboot
    echo would reboot now... (TODO)

}



# Check if this script is already running
kill -0 $(cat "$pidfile" 2> /dev/null) 2> /dev/null
if [[ "$?" == "0" ]]; then
    echo "Script is already running, exiting"
    exit 1
else
    [[ -f "$pidfile" ]] && rm "$pidfile"
fi
echo $$ > "$pidfile"



run $1 $2
inform_webinterface

rm "$pidfile"

