#!/bin/ash

#set -xv

# variables
opkg="/bin/opkg -f /etc/opkg-enigmabox.conf"
pidfile="/var/run/updater.pid"
dynamic_output="/tmp/dynamic_output"



run() {
    background=""

    if [[ "$2" == "bg" ]]; then
        > "$dynamic_output"
        background=1
    fi

    if [[ "$1" == "check" ]]; then
        if [[ "$background" == 1 ]]; then
            (updater_check > "$dynamic_output") &
        else
            updater_check
        fi
    elif [[ "$1" == "apply" ]]; then
        if [[ "$background" == 1 ]]; then
            (updater_apply > "$dynamic_output") &
        else
            updater_apply
        fi
    fi

}

updater_check() {
    $opkg update
    $opkg list-upgradable
}



# Check if this script is already running
kill -0 $(cat "$pidfile" 2> /dev/null) 2> /dev/null
if [[ "$?" == "0" ]]; then
    echo "Script is already running, exiting"
    exit 1
else
    [[ -f "$pidfile" ]] && rm "$pidfile"
fi
echo $$ > "$pidfile"



run $1 $2

rm "$pidfile"

